apiVersion: v1
kind: Service
id: ${MYSQLNAME}-${NODE}
metadata:
  lables:
    name: ${MYSQLNAME}-${NODE}
  name: ${MYSQLNAME}-${NODE}
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
    - port: 4444
      targetPort: 4444 
      name: state-snapshot-transfer
    - port: 4567
      targetPort: 4567
      name: replication-traffic 
    - port: 4568
      targetPort: 4568 
      name: incremental-state-transfer 
  selector:
    name: ${MYSQLNAME}-${NODE}
labels: 
  name: ${MYSQLNAME}-${NODE}