apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: ${MYSQLNAME}-${NODE}
  name: ${MYSQLNAME}-${NODE} 
spec:
  replicas: 1
  selector:
    name: ${MYSQLNAME}-${NODE}
  template:
    metadata:
      labels:
        name: ${MYSQLNAME}-${NODE}
    spec:
      containers:
        - resources:
            limits: 
              cpu: 0.3
          image: capttofu/percona_xtradb_cluster_5_6:latest
          name: ${MYSQLNAME}-${NODE}
          ports:
            - containerPort: 3306
              name: mysql
            - containerPort: 4444
            - containerPort: 4567
            - containerPort: 4568
          env:
            - name: GALERA_CLUSTER
              value: "true"
            - name: WSREP_CLUSTER_ADDRESS
              value: gcomm://
            - name: WSREP_SST_USER
              value: sst
            - name: WSREP_SST_PASSWORD
              value: sst
            - name: MYSQL_USER
              value: mysql
            - name: MYSQL_PASSWORD
              value: mysql
            - name: MYSQL_ROOT_PASSWORD
              value: thundercats
            - name: PXC_NODE1_SERVICE_HOST
              value: ${MYSQLNAME}-node1
            - name: PXC_NODE2_SERVICE_HOST
              value: ${MYSQLNAME}-node2
            - name: PXC_NODE3_SERVICE_HOST
              value: ${MYSQLNAME}-node3